server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.get_dealerships, name='index'),

    # path for about view
    path(route='about/', view=views.about, name='about'),

    # path for contact us view
    path(route='contact/', view=views.contact, name='contact'),

    # path for registration
    path(route='registration/', view=views.registration_request, name='registration'),

    # path for login
    path(route='login/', view=views.login_request, name='login'),

    # path for logout
    path(route='logout/', view=views.logout_request, name='logout'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>/', view=views.get_dealer_details, name='dealer_details'),

    # path for adding a new review view
    path(route='dealer/<int:dealer_id>/add-review/', view=views.add_review, name="add_review")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
import datetime
from django.db import models
from django.utils.timezone import now


# Car Make model
class CarMake(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(null=True, max_length=500)

    def __str__(self):
        return self.name

# Car Model model


class CarModel(models.Model):
    car_make = models.ForeignKey(CarMake, null=True, on_delete=models.CASCADE)
    name = models.CharField(null=False, max_length=50)
    dealer_id = models.IntegerField(null=True)

    SEDAN = "Sedan"
    SUV = "SUV"
    WAGON = "Wagon"
    SPORT = "Sport"
    COUPE = "Coupe"
    MINIVAN = "Mini"
    VAN = "Van"
    PICKUP = "Pickup"
    TRUCK = "Truck"
    BIKE = "Bike"
    SCOOTER = "Scooter"
    OTHER = "Other"
    CAR_CHOICES = [(SEDAN, "Sedan"), (SUV, "SUV"), (WAGON, "Station wagon"), (SPORT, "Sports Car"),
                   (COUPE, "Coupe"), (MINIVAN, "Mini van"), (VAN,
                                                             "Van"), (PICKUP, "Pick-up truck"),
                   (TRUCK, "Truck"), (BIKE, "Motor bike"), (SCOOTER, "Scooter"), (OTHER, 'Other')]
    model_type = models.CharField(
        null=False, max_length=15, choices=CAR_CHOICES, default=SEDAN)

    YEAR_CHOICES = []
    for r in range(1969, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r, r))

    year = models.IntegerField(
        ('year'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)

    def __str__(self):
        return self.name + ", " + str(self.year) + ", " + self.model_type


# A plain Python class to hold dealer data
class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, state, zip):
        self.address = address
        self.city = city
        self.full_name = full_name  # Full name of dealership
        self.id = id  # Dealership id
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.st = st  # State alpha code
        self.state = state  # Full state name
        self.zip = zip
        self.idx = 0

    def __str__(self):
        return self.full_name + ", " + self.state


# A plain Python class to hold review data
class DealerReview:
    def __init__(self, dealership, id, name, purchase, review, car_make=None, car_model=None, car_year=None, purchase_date=None, sentiment="neutral"):
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.dealership = dealership
        self.id = id  # The id of the review
        self.name = name  # Name of the reviewer
        self.purchase = purchase  # Did the reviewer purchase the car? bool
        self.purchase_date = purchase_date
        self.review = review  # The actual review text
        self.sentiment = sentiment  # Watson NLU sentiment analysis of review

    def __str__(self):
        return "Reviewer: " + self.name + " Review: " + self.review

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel
from .restapis import get_dealer_by_id, get_dealers_from_cf, get_dealers_by_state, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Getting an instance of a logger
logger = logging.getLogger(__name__)


# View to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://9bebcb01.eu-de.apigw.appdomain.cloud/api/dealership"
        # Get dealers from the Cloudant DB
        context["dealerships"] = get_dealers_from_cf(url)

        # dealer_names = ' '.join([dealer.short_name for dealer in context["dealerships"]])
        # return HttpResponse(dealer_names)

        return render(request, 'djangoapp/index.html', context)

# View to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# View to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)


# View to handle sign in request
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)


# View to handle sign out request
def logout_request(request):
    # Get the user object based on session id in request
    print("Logging out `{}`...".format(request.user.username))
    # Logout user in the request
    logout(request)
    # Redirect user back to course list view
    return redirect('djangoapp:index')


# View to handle sign up request
def registration_request(request):
    context = {}
    # If it is a GET request, just render the registration page
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    # If it is a POST request
    elif request.method == 'POST':
        # Get user information from request.POST
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            # Check if user already exists
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))
        # If it is a new user
        if not user_exist:
            # Create user in auth_user table
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            # Login the user and redirect to course list page
            login(request, user)
            return redirect("/djangoapp/")
        else:
            return render(request, 'djangoapp/registration.html', context)


# View to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = 'https://9bebcb01.eu-de.apigw.appdomain.cloud/api/review'
        reviews = get_dealer_reviews_from_cf(url, dealer_id=dealer_id)
        context = {
            "reviews":  reviews, 
            "dealer_id": dealer_id
        }

        return render(request, 'djangoapp/dealer_details.html', context)


# View to submit a new review
def add_review(request, dealer_id):
    # User must be logged in before posting a review
    if request.user.is_authenticated:
        # GET request renders the page with the form for filling out a review
        if request.method == "GET":
            url = f"https://5b93346d.us-south.apigw.appdomain.cloud/dealerships/dealer-get?dealerId={dealer_id}"
            # Get dealer details from the API
            context = {
                "cars": CarModel.objects.all(),
                "dealer": get_dealer_by_id(url, dealer_id=dealer_id),
            }
            return render(request, 'djangoapp/add_review.html', context)

        # POST request posts the content in the review submission form to the Cloudant DB using the post_review Cloud Function
        if request.method == "POST":
            form = request.POST
            review = dict()
            review["name"] = f"{request.user.first_name} {request.user.last_name}"
            review["dealership"] = dealer_id
            review["review"] = form["content"]
            review["purchase"] = form.get("purchasecheck")
            if review["purchase"]:
                review["purchase_date"] = datetime.strptime(form.get("purchasedate"), "%m/%d/%Y").isoformat()
            car = CarModel.objects.get(pk=form["car"])
            review["car_make"] = car.car_make.name
            review["car_model"] = car.name
            review["car_year"] = car.year
            
            # If the user bought the car, get the purchase date
            if form.get("purchasecheck"):
                review["purchase_date"] = datetime.strptime(form.get("purchasedate"), "%m/%d/%Y").isoformat()
            else: 
                review["purchase_date"] = None

            url = "https://9bebcb01.eu-de.apigw.appdomain.cloud/api/review"  # API Cloud Function route
            json_payload = {"review": review}  # Create a JSON payload that contains the review data

            # Performing a POST request with the review
            result = post_request(url, json_payload, dealerId=dealer_id)
            if int(result.status_code) == 200:
                print("Review posted successfully.")

            # After posting the review the user is redirected back to the dealer details page
            return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

    else:
        # If user isn't logged in, redirect to login page
        print("User must be authenticated before posting a review. Please log in.")
        return redirect("/djangoapp/login")

server/djangoapp/templates/djangoapp/about.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="skeleton-heading">About Us</h1>
        <div class="p-4 justify-content-center">
            <p>
                Welcome to Best Cars, 
                home to the best cars in North America. 
                We sell domestic and imported cars at reasonable prices.
            </p>
            </br>
            <p>
                Best Cars dealership was founded in 2003 after a decision was made to 
                move from the trade side of the business into the retail side. A family business 
                employing four generations of the same family and over 30 staff. 
                We at Best Cars dealership have built our reputation on customer service with over 50% 
                of the business being loyal customers who keep coming back to us. 
                We are a 'Highly rated' Auto Trader dealer and a 'Top rated' Car Gurus dealer.
                We have over 180 cars on our site that cover a wide range of different types, models and 
                styles, together with a purpose-built workshop, valet bay & 'smart' repair centre.
                The staff bring with them a wealth of experience from across the motor industry 
                adding up to over 130 years of motor trade knowledge and experience.
                Most of our staff have been with us long term- an unusual feat in the motor trade 
                so the salesman you purchase your car from is usually here if you come back to see us. 
                Our workshop staff have been with us since the beginning. 
                
                We found fame in 2009 when our cars were used in the filming of "The Fast and The Furious". 
                Our cars are priced from £3,000 - £150,000 and we 
                carry a stock of over 180 cars. If we don't have what you want we 
                can usually find it for you. We also specialise in Finance (subject to status) 
                for all kinds of credit ratings and deal with most of the major companies and specialist brokers. 
                Need a warranty? We offer up to 4 years Trading Standards Approved warranty on the majority of 
                our stock with repair centres across the UK. 
            </p>
            </br>
            <p><a style="color:black; font-weight: bold;" href="{% url 'djangoapp:contact' %}">Get in touch with us today!</a></p>
    </div>    
{% endblock %}

server/djangoapp/templates/djangoapp/add_review.html
{% extends 'base.html' %}

{% block content %}

    <main class="container">
        <h1>New review</h1>
        <h4><i>for {{dealer.full_name}}</i></h4>
        <br>
        <!--review form -->
        <form action="/djangoapp/dealer/{{dealer.id}}/add-review/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="content"><b>Enter the review content:</b></label>
                <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                <label for="purchasecheck">Did you purchase the car? </label>
            </div>
            <div class="form-group">
                <label for="car">Select your car:</label>
                <select name="car" id="car" class="form-select">
                    {% for car in cars %}
                        <option selected value={{car.id}}>{{car.car_make.name}} {{car.name}} {{ car.year }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" data-provide="datepicker">
                <label for="purchasedate">Select your purchase date (mm/dd/yyyy):</label>
                <input class="date-own form-control" type="text" name="purchasedate" id="purchasedate">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </main>
    <script type="text/javascript">
        $('.date-own').datepicker({
           format: 'mm/dd/yyyy'
         });
   </script>

{% endblock %}

server/djangoapp/templates/djangoapp/contact.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="heading-txt" style="font-size: 2em; margin-bottom: 3%; text-align: center;">Contact</h1>
        <div style="margin-top: 5%;display: flex; justify-content: space-evenly; flex-wrap: wrap;">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">Contact Information</div>
            <div class="card-body">
                <h5 class="card-title">Customer Care</h5>
                <p class="card-text">Name: Michael F. Mann </br> Mobile: 41373734689 </br> Email: michael@dealership.com </p>
            </div>
        </div>
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">Contact Information</div>
            <div class="card-body">
                <h5 class="card-title">Lead Salesman</h5>
                <p class="card-text">Name: Bobby B. Grosse </br> Mobile: 125678892 </br> Email: bobby@dealership.com </p>
            </div>
        </div>
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">Contact Information</div>
            <div class="card-body">
                <h5 class="card-title">Customer Care</h5>
                <p class="card-text">Name: Justin Fields </br> Mobile: 557844332 </br> Email: justin@dealership.com </p>
            </div>
        </div>
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">Contact Information</div>
            <div class="card-body">
                <h5 class="card-title">Customer Care</h5>
                <p class="card-text">Name: Jessica Bunnie </br> Mobile: 833834562 </br> Email: jess@dealership.com </p>
            </div>
        </div>
                <div class="card text-white bg-dark mb-2" style="max-width: 40rem;">
            <div class="card-header">Visiting Address</div>
            <div class="card-body">
                <h5 class="card-text">Best Cars HQ</br></br>Sidewinder Avenue 369, Austin, TX, US</br></br></h5>
                <p class="card-text">Phone: 003721435476 </br> Email: info@dealership.com </p>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

server/djangoapp/templates/djangoapp/dealer_details.html
{% extends 'base.html' %}
{% block content %}
    {% if reviews %}
        {% if user.is_authenticated %}
            <div style="margin: 10px;">
                <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer_id %}"><b>Write a car review</b></a>
            </div>
        {% endif %}
        <div class="card-columns">
            {% for review in reviews %}
                {% if review.car_make %}
                <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                    <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                    <div class="card-body" style="text-align: center;">
                        <h5 class="card-title" style="display: inline-block;">{{ review.car_make }}, {{ review.car_model }}</h5>
                        <h5 class="card-title">{{ review.car_year }}</h5>
                        <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                    </div>
                </div>
                <!-- some review data may be missing , using default values-->
                {% else %}
                <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                    <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                    <div class="card-body" style="text-align: center;">
                        <h5 class="card-title" style="display: inline-block;">Review</h5>
                        <h5 class="card-title"></h5>
                        <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>

    {% else %}
        <p></br>There are no reviews for this dealership.</br></p>
        {% if user.is_authenticated %}
            <div style="margin: 10px;">
                <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer_id %}"><b>Write a car review</b></a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

server/djangoapp/templates/djangoapp/index.html
{% extends 'base.html' %}

{% block content %}
    <h1></br>Our dealerships</h3>
    <!-- Dealer table -->
    <div class="container">
        <table class="table" id="table" data-filter-control="true">
            <thead>
                <tr>
                    <th data-field="id">ID</th>
                    <th data-field="name">Dealer Name</th>
                    <th data-field="city">City</th>
                    <th data-field="address">Address</th>
                    <th data-field="zip">Zip</th>
                    <th data-field="state" data-filter-control="select">State</th>
                </tr>
            </thead>
            <tbody>
                {% for dealer in dealerships %}
                <tr>
                    <td>{{dealer.id}}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td>{{dealer.city}}</td>
                    <td>{{dealer.address}}</td>
                    <td>{{dealer.zip}}</td>
                    <td>{{dealer.state}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- turn-on filter control for the table -->
    <script>
        $(function(){
            $('#table').bootstrapTable()
        })
    </script>
{% endblock %}

server/djangoapp/templates/djangoapp/login.html
{% extends 'base.html' %}

{% block content %}
    <h3></br>This is the login page.</h3>

    
    <!-- Login form -->
    <form action="{% url 'djangoapp:login' %}" method="post">
        {% csrf_token %}
        <div class="container">
            <h1>Login</h1>
            <div class="form-group"> 
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> 
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> 
            </div>
            {% if message %}
              <div class="alert alert-warning"> 
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> 
        </div>
    </form>

{% endblock %}

server/djangoapp/templates/djangoapp/registration.html
{% extends 'base.html' %}

{% block content %}
    <!-- Registration form -->
    <form action="{% url 'djangoapp:registration' %}" method="post">
        <div class="container">
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group">
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required>
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required>
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required>
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required>
                {% if message %}
                <div class="alert alert-warning">
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button>
            </div>
        </div>
    </form>
{% endblock %}